using System.Text;
using PowerPlug.BaseCmdlets;

namespace PowerPlug.Engines.Byname
{
    public class SetBynameCreator : CreatableBynameCreatorBase
    {
        public SetBynameCreator(WritableBynameBase cmdlet) : base(cmdlet) { }

        public sealed override void Execute()
        {
            var rc = base.RunCommand(SetAliasCommand);
            foreach (var p in rc)
            {
                AliasCmdlet.WriteObject(p);
            }

            var sb = new StringBuilder("\n# Autogenerated Profile Alias - Do Not Modify\n");

            if (GetAliasValueType(AliasCmdlet) is FunctionValueType ft)
            {
                sb.Append($"function {AliasCmdlet.Value} {{ {ft.ScriptBlock} }}\n");
            }

            sb.Append("New-Alias")
                .Append($" -Name {AliasCmdlet.Name}")
                .Append($" -Value {AliasCmdlet.Value}")
                .Append($" -Option {AliasCmdlet.Option}")
                .Append($" -Scope {AliasCmdlet.Scope}")
                .AppendIf(" -PassThru", AliasCmdlet.PassThru)
                .AppendIf(" -Force", AliasCmdlet.Force)
                .AppendIf(" -WhatIf", AliasCmdlet.WhatIf)
                .AppendIf(" -Confirm", AliasCmdlet.Confirm)
                .AppendIf($" -Description {AliasCmdlet.Description}", AliasCmdlet.Description != string.Empty);

            RemoveBynameCreator.RemoveBynameFromFile(this.AliasCmdlet, ProfileInfo);
            ProfileInfo.WriteLine(sb.ToString());
        }
    }
}
