version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      test-dependencies:
        patterns:
          - "xunit*"
          - "NSubstitute*"
          - "Microsoft.NET.Test.Sdk"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
